language: python

python:
        - 2.7
        - 3.5
        - 3.6

# install dependencies
install:
        - pip install -r requirements/dev.txt

# run scripts
script:
        - coverage erase
        - coverage run test_webapp.py && coverage html
        - pylint -r y webapp.py
        - python -m unittest discover
        - behave

after_success:
        - codecov
